name: handle-env
on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          env: |
            FOO_VAR=42
            BAR_VAR=43
            BAZ_VAR=44
      - name: Print .env
        run: cat .env
